-- Busy Multicare CMS schema
-- Run in Supabase SQL Editor

-- Blog posts table
CREATE TABLE IF NOT EXISTS blog_posts (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  title text NOT NULL,
  excerpt text NOT NULL,
  image text,
  images text[] DEFAULT '{}',
  date date,
  slug text NOT NULL UNIQUE,
  category text,
  content text,
  author text,
  status text DEFAULT 'draft',
  created_at timestamptz DEFAULT now()
);

-- Blog posts: add images array (fallback if table already existed)
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS images text[] DEFAULT '{}';
-- Awards table
CREATE TABLE IF NOT EXISTS awards (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  year text DEFAULT '',
  images text[] DEFAULT '{}',
  image text,
  sort_order int DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

-- Site content (home page CMS + global settings)
CREATE TABLE IF NOT EXISTS site_content (
  id text PRIMARY KEY,
  content jsonb NOT NULL DEFAULT '{}',
  updated_at timestamptz DEFAULT now()
);

-- RLS + grants (anon read, authenticated write)
ALTER TABLE awards ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE blog_posts ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT ON awards TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON awards TO authenticated;
GRANT SELECT ON site_content TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON site_content TO authenticated;
GRANT SELECT ON blog_posts TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON blog_posts TO authenticated;

DROP POLICY IF EXISTS "Public read awards" ON awards;
DROP POLICY IF EXISTS "awards_select_public" ON awards;
CREATE POLICY "awards_select_public" ON awards FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Auth write awards" ON awards;
DROP POLICY IF EXISTS "awards_insert_authenticated" ON awards;
CREATE POLICY "awards_insert_authenticated" ON awards FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "awards_update_authenticated" ON awards;
CREATE POLICY "awards_update_authenticated" ON awards FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "awards_delete_authenticated" ON awards;
CREATE POLICY "awards_delete_authenticated" ON awards FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Public read blog_posts" ON blog_posts;
DROP POLICY IF EXISTS "blog_posts_select_public" ON blog_posts;
CREATE POLICY "blog_posts_select_public" ON blog_posts FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Auth write blog_posts" ON blog_posts;
DROP POLICY IF EXISTS "blog_posts_insert_authenticated" ON blog_posts;
CREATE POLICY "blog_posts_insert_authenticated" ON blog_posts FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "blog_posts_update_authenticated" ON blog_posts;
CREATE POLICY "blog_posts_update_authenticated" ON blog_posts FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "blog_posts_delete_authenticated" ON blog_posts;
CREATE POLICY "blog_posts_delete_authenticated" ON blog_posts FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Public read site_content" ON site_content;
DROP POLICY IF EXISTS "Auth write site_content" ON site_content;
DROP POLICY IF EXISTS "site_content_select_public" ON site_content;
CREATE POLICY "site_content_select_public" ON site_content FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "site_content_insert_authenticated" ON site_content;
CREATE POLICY "site_content_insert_authenticated" ON site_content FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "site_content_update_authenticated" ON site_content;
CREATE POLICY "site_content_update_authenticated" ON site_content FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
DROP POLICY IF EXISTS "site_content_delete_authenticated" ON site_content;
CREATE POLICY "site_content_delete_authenticated" ON site_content FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL);

-- Seed placeholders (admin publishes full JSON from app defaults)
INSERT INTO site_content (id, content) VALUES ('home', '{}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO site_content (id, content) VALUES ('global', '{}'::jsonb)
ON CONFLICT (id) DO NOTHING;
