-- Busy Multicare CMS schema
-- Run in Supabase SQL Editor

-- Blog posts: add images array
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS images text[] DEFAULT '{}';

-- Awards table
CREATE TABLE IF NOT EXISTS awards (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  year text DEFAULT '',
  images text[] DEFAULT '{}',
  image text,
  sort_order int DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

-- Site content (home page CMS + global settings)
CREATE TABLE IF NOT EXISTS site_content (
  id text PRIMARY KEY,
  content jsonb NOT NULL DEFAULT '{}',
  updated_at timestamptz DEFAULT now()
);

-- RLS + grants (anon read, authenticated write)
ALTER TABLE awards ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_content ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT ON awards TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON awards TO authenticated;
GRANT SELECT ON site_content TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON site_content TO authenticated;

DROP POLICY IF EXISTS "Public read awards" ON awards;
CREATE POLICY "awards_select_public" ON awards FOR SELECT TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Auth write awards" ON awards;
CREATE POLICY "awards_insert_authenticated" ON awards FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "awards_update_authenticated" ON awards FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "awards_delete_authenticated" ON awards FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Public read site_content" ON site_content;
DROP POLICY IF EXISTS "Auth write site_content" ON site_content;
CREATE POLICY "site_content_select_public" ON site_content FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "site_content_insert_authenticated" ON site_content FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "site_content_update_authenticated" ON site_content FOR UPDATE TO authenticated USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "site_content_delete_authenticated" ON site_content FOR DELETE TO authenticated USING (auth.uid() IS NOT NULL);

-- Seed placeholders (admin publishes full JSON from app defaults)
INSERT INTO site_content (id, content) VALUES ('home', '{}'::jsonb)
ON CONFLICT (id) DO NOTHING;

INSERT INTO site_content (id, content) VALUES ('global', '{}'::jsonb)
ON CONFLICT (id) DO NOTHING;
